version: "3.4"

services:
  lung-vitality:
    extends:
      file: lung-vitality/docker/docker-services.prod.yml
      service: lung-vitality
    pull_policy: build
    restart: always

  smart-lungs:
    extends:
      file: smart-lungs/docker/docker-services.prod.yml
      service: smart-lungs
    pull_policy: build
    restart: always

  api:
    extends:
      file: api/docker-services.yml
      service: api
    pull_policy: build
    restart: always

networks:
  default:
    name: nginxproxymanager_default
    external: true
