version: "3"

services:
  lung-vitality:
    container_name: lung-vitality
    build:
      context: ../
      dockerfile: prod.Dockerfile
      # args:
      #   ARG NEXT_MY_ENV_VAR: ${ARG NEXT_MY_ENV_VAR}
