version: "3"

services:
  smart-lungs:
    container_name: smart-lungs
    build:
      context: ../
      dockerfile: prod.Dockerfile
      # args:
      #   ARG NEXT_MY_ENV_VAR: ${ARG NEXT_MY_ENV_VAR}
